Repository pikers/piker, pull requests merged in 2023-02, with the labels that each got.

#454 `ib`: fix cmdtys feeds
  piker/brokers/ib/api.py
  setup.py
Labels: broker-backend, brokers-can-smbz

#449 Multi symbol input (support)
  piker/data/feed.py
  piker/ui/_chart.py
  piker/ui/_display.py
  piker/ui/_flows.py
  piker/ui/_fsp.py
  piker/ui/_ohlc.py
  piker/ui/_position.py
  piker/ui/_style.py
  piker/ui/order_mode.py
Labels: new-enhancement, UI, viz, graphics

#457 Use new msgspec default factories
  piker/clearing/_messages.py
  piker/ui/_display.py
  piker/ui/_pathops.py
Labels: bug

#460 Fix crash on notification daemon not found
  piker/ui/_notify.py
Labels: bug

#453 Overlays interaction latency tuning
  piker/_daemon.py
  piker/_profile.py
  piker/data/_formatters.py
  piker/data/_m4.py
  piker/data/_pathops.py
  piker/data/feed.py
  piker/data/flows.py
  piker/pp.py
  piker/ui/_chart.py
  piker/ui/_cursor.py
  piker/ui/_curve.py
  piker/ui/_dataviz.py
  piker/ui/_display.py
  piker/ui/_fsp.py
  piker/ui/_interaction.py
  piker/ui/_ohlc.py
  piker/ui/_overlay.py
  piker/ui/_render.py
  piker/ui/_search.py
Labels: UI, viz, graphics, perf

#465 `loglevel` to `open_test_pikerd()` via `--ll <level>` flag
  piker/brokers/__init__.py
  piker/brokers/data.py
  piker/clearing/_client.py
  piker/data/feed.py
  tests/conftest.py
  tests/test_feeds.py
  tests/test_questrade.py
  tests/test_services.py
Labels: dependencies, testing

#469 Fix `loglevel` not getting propagated to `emsd`
  piker/ui/_display.py
  piker/ui/order_mode.py
Labels: bug
